### ISSUE TITLE
Add warning for #65 changes

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/LsqFit.jl#66]
Before tagging a new version, the deprecation of the old meaning of functions changed in #65 should be handled. 

I'm not sure we can handle it perfectly, but it should definitely be mentioned somewhere.

**Comment by iewaij** [comment]
The major change in #65 is `estimate_errors()` which used to estimate standard errors. We can depreciate it using `@deprecate` to ask users use `standard_error()` instead.

Probably it's better idea to leave `estimate_errors()` do the same job as `standard_error()` rather than printing out fitting results, and add `confidence_interval()` to return confidence intervals.

**Comment by blakejohnson** [comment]
@iewaij this issue is now resolved, right?

**Comment by iewaij** [comment]
@blakejohnson yes, feel free to close this.
