### ISSUE TITLE
Delayed gratification and geodesic acceleration in Levenburg-Marquardt

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/LsqFit.jl#88]
I found this paper to be quite interesting. https://arxiv.org/pdf/1010.1449.pdf

**Comment by pkofod** [comment]
Cool stuff. Haven’t read the details, but the overall idea is interesting.

**Comment by blakejohnson** [comment]
I actually started this project with the intent of prototyping geodesic acceleration. Obviously, I never got around to it. But, I'd love to see it land in this package.

**Comment by pkofod** [comment]
The mu and nu letters represent what exactly? I'm a bit confused that they don't write the jacobian of residuals and hessian of the cost using theta. Is it just because they don't necessarily consider all the parameters in theta as ones to optimize over?

**Comment by Magalame** [comment]
There is a follow-up paper: https://arxiv.org/pdf/1201.5885.pdf
Along with a Fortran implementation: https://sourceforge.net/projects/geodesiclm/ (ref. 13 in the follow up paper)

I'll try to translate it into Julia and see what it yields

**Comment by pkofod** [comment]
The packages are here https://pulsar.byu.edu/Modeling/Geometry.jl/ and https://pulsar.byu.edu/Modeling/Models.jl 

However, I think it's better to go from the sourceforge project unless you want to implement it directly from the paper instead. I think the latter might be a good idea, but it's also a bigger job.

(hoping I'm tagging the right guy, bit appears to be from the repos @mktranstrum )

**Comment by Magalame** [comment]
Oh thanks a lot for the links, it'll still be a point comparison. When reading the paper my main interrogation was how to compute the acceleration considering only the model and the Jacobian, so that'll be helpful!

I'll try to implement the algorithm as outlined at the end of the initial paper. Considering we already have an implementation of LM, it shouldn't be too much of a hassle, I hope

**Comment by pkofod** [comment]
>  LM, it shouldn't be too much of a hassle, I hope

famous last words :)

**Comment by Magalame** [comment]
> famous last words :)

:( 

It does seem like we'll need the Hessian, as we'll need the directional second derivative (https://imgur.com/a/O8ZWQCK it's what the `Avv`function computes and stores in `acc` ), which can be computed by `v^T H v`, fortunately there is `TwiceDifferentiable`, but it'll be interesting to see what would be the memory cost of using a non-analytic Hessian.

**Comment by Magalame** [comment]
Hmmm, seems like `TwiceDifferentiable` doesn't support multivariate output, so that'll be fun.

**Comment by pkofod** [comment]
The hessian is not the tensor that is the second derivative of the residual though, it's the second derivative of the actual objective, so `f(x) = sum(abs2, residual)`, right? It's been a while since I read the papers, so I don't remember the exact details.

**Comment by Magalame** [comment]
I thought that since the Jacobian is the first derivative of the residuals, I thought it'd be the same for the Hessian, critical mistake. They don't use the Hessian in the paper, but I thought it could be a nice way to obtain the tensor of directional second derivative. 
See [here](https://imgur.com/a/FzQZ4dF) (the line just above 4.), just to check, `\del_mu \del_\nu r`is a tensor right?

**Comment by pkofod** [comment]
it's been on master for a couple of months, so closing here, and hope to do a new release soon
